services:
  meshcentral:
    image: typhonragewind/meshcentral:1.1.53
    restart: unless-stopped
    hostname: meshcentral
    container_name: meshcentral
    networks:
      - traefik-net
    volumes:
      - /data/meshcentral/data:/opt/meshcentral/meshcentral-data
      - ./config.json:/opt/meshcentral/meshcentral-data/config.json:ro
      - /data/meshcentral/user_files:/opt/meshcentral/meshcentral-files
      - /data/meshcentral/backups:/opt/meshcentral/meshcentral-backups
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.meshcentral.rule=Host(`mesh.thomega.fr`)'
      - 'traefik.http.routers.meshcentral.entryPoints=websecure'
      - 'traefik.http.services.meshcentral.loadbalancer.server.port=443'
      - 'traefik.http.services.meshcentral.loadbalancer.server.scheme=https'
      - 'traefik.docker.network=traefik-net'

networks:
  traefik-net:
    external: true
    name: traefik-net
