services:
  homeassistant:
    container_name: homeassistant
    hostname: homeassistant
    image: ghcr.io/home-assistant/home-assistant:2026.3
    volumes:
      - /data/Homeassistant/core:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus
    network_mode: host
    restart: always
    privileged: true
    cap_add:
      - NET_ADMIN
      - NET_RAW
