services:
  homeassistant:
    container_name: homeassistant
    hostname: homeassistant
    image: ghcr.io/home-assistant/home-assistant:2026.3
    volumes:
      - /data/Homeassistant/core:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus
    network_mode: host
    restart: unless-stopped
    privileged: true
    cap_add:
      - NET_ADMIN
      - NET_RAW
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.homeassistant.rule=Host(`home.thomega.fr`)'
      - 'traefik.http.routers.homeassistant.entryPoints=websecure'
      - 'traefik.http.services.homeassistant.loadbalancer.server.port=8123'
      - 'traefik.docker.network=traefik-net'
