services:
  homeassistant:
    container_name: homeassistant
    hostname: homeassistant
    image: ghcr.io/home-assistant/home-assistant:2026.5
    volumes:
      - /data/Homeassistant/core:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus
    network_mode: host
    restart: unless-stopped
    privileged: true
    cap_add:
      - NET_ADMIN
      - NET_RAW
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.homeassistant.rule=Host(`home.thomega.fr`)'
      - 'traefik.http.routers.homeassistant.entryPoints=websecure'
      - 'traefik.http.routers.homeassistant-sw-block.rule=Host(`home.thomega.fr`) && Path(`/service_worker.js`)'
      - 'traefik.http.routers.homeassistant-sw-block.entryPoints=websecure'
      - 'traefik.http.routers.homeassistant-sw-block.priority=1000'
      - 'traefik.http.routers.homeassistant-sw-block.service=homeassistant'
      - 'traefik.http.routers.homeassistant-sw-block.middlewares=homeassistant-sw-block-path'
      - 'traefik.http.middlewares.homeassistant-sw-block-path.replacepath.path=/__blocked_service_worker__.js'
      - 'traefik.http.services.homeassistant.loadbalancer.server.port=8123'
      - 'traefik.docker.network=traefik-net'
