services:
  diun:
    image: crazymax/diun:4.30.0
    container_name: diun
    command: serve
    volumes:
      - /data/diun:/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DIUN_DB_PATH=/data/diun.db
      - DIUN_PROVIDERS_DOCKER=true
      - DIUN_PROVIDERS_DOCKER_WATCHBYDEFAULT=true
      - DIUN_WATCH_SCHEDULE=0 */6 * * *
      - DIUN_WATCH_FIRSTCHECKNOTIF=false
      - DIUN_NOTIF_DISCORD_WEBHOOKURL=${DIUN_NOTIF_DISCORD_WEBHOOKURL}
    restart: unless-stopped
