services:
  vscode:
    image: docker.io/codercom/code-server:latest
    restart: unless-stopped
    container_name: vscode
    user: "0:0"
    command: ["--auth", "none", "/home/thome/homelab-compose"]
    environment:
      - TZ=Europe/Paris
      - HOME=/home/thome
    volumes:
      - /data:/data
      - /data/vscode/config:/home/thome/.config
      - /data/vscode/local:/home/thome/.local
      - /home/thome:/home/thome
      # --- THE MAGIC MOUNTS TO ACCESS THE HOST ---
      - /var/run/docker.sock:/var/run/docker.sock # Gives the container access to your host's Docker engine
      - /usr/bin/docker:/usr/bin/docker           # Mounts the host's docker CLI binary directly into the container
      - /usr/libexec/docker/cli-plugins:/usr/libexec/docker/cli-plugins
    networks:
      - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vscode.rule=Host(`vscode.thomega.fr`)"
      - "traefik.http.routers.vscode.entrypoints=websecure"
      - "traefik.http.routers.vscode.tls.certresolver=letsencrypt"
      - "traefik.http.services.vscode.loadbalancer.server.port=8080"
      - "traefik.http.routers.vscode.middlewares=authentik-auth@docker"
    healthcheck:
      test: ["CMD", "curl", "-s", "-o", "/dev/null", "http://localhost:8080/"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    security_opt:
      - seccomp:unconfined

networks:
  traefik-net:
    external: true
